// ── BAKER STREET NETWORK CONTACTS ────────────────────────────────────────────
// Your 14 direct contacts — brokers, lenders, attorneys, operators.
// Edit this file to add new contacts, update deal histories, or add notes.
// Each contact: name, firm, role, markets, notes, dealHistory[]

const BS_NETWORK_CONTACTS = [
{name:"Paul Salvo",         firm:"SC Capital Investments",        role:"CEO & Founder",                             markets:"Suburban Philadelphia PA, NJ",
      notes:"Grew up in family construction business — took over Salvo General Contracting (SGC) and Salvo Waterproofing & Masonry 20+ years ago. Started acquiring small suburban Philadelphia MF properties around 2010 and scaled into a full platform. Founded SC Capital Investments in 2022 with CFO Chris Chilla; added Wayne Everett as Partner/CIO (20+ years RE, $1B+ in MF acquisitions). Vertically integrated: SC Capital (acquisitions) + DMC Property Management (operations) + Salvo General Contracting (construction/value-add). Based in Norristown PA. Portfolio is 24+ suburban Philadelphia MF properties managed by DMC — Trappe, Laureldale, Bridgeport, Morrisville, Collegeville, Fairless Hills, King of Prussia, Norristown, Pottstown, Souderton, Lansdale, South Coatesville, Reading, Hatfield, West Reading, Downingtown. Focuses on value-add and workforce housing in suburban Montgomery, Chester, Berks, and Bucks counties. No formal degree information found publicly — background is operator/builder, not finance. BAKER STREET CONNECTION: Paul is a direct private operator — exactly the type of sponsor Baker Street can advise on recaps, debt restructuring, or distressed situations at the property level. DMC management platform means he also sees deal flow from other owners."
    },
    {name:"Erin Miller",        firm:"Newmark",                       role:"Exec Managing Director, Multifamily Capital Markets", markets:"Philadelphia PA",
      notes:"Joined Newmark Jan 2018. 20+ years multihousing brokerage. $10B+ career transactions. Prior: SVP JLL, led Philly multihousing investment sales. Before that: Moran & Company (Southern CA, then DC). Harvard Kennedy School MPP. Co-leads Newmark Philly MF investment sales with Lizann McGowan. Works on same platform as Steve Comly (debt). BAKER STREET CONNECTION: Erin is on same Newmark platform as Jim Badolato and Steve Comly — debt+sales combos frequent. She brokered The Drake (2025) where Lument (John Hurley's firm) arranged the financing — direct link across Baker Street's network.",
      dealHistory:[
        {property:"1500 Locust St",address:"1500 Locust St, Rittenhouse Square, Philadelphia PA",type:"Multifamily",year:2022,units:612,amount:233000000,role:"Broker (seller rep)",seller:"Barings (institutional client)",buyer:"Fairstead",notes:"$233M — largest single-asset multifamily sale in Philadelphia history. 45-story mixed-use. 828,679 SF. 7,770 SF retail, 398-space garage. Fairstead's first Philadelphia acquisition. Miller + Lizann McGowan repped seller. Barings had held 30+ years."},
        {property:"The Drake",address:"1512 Spruce St, Center City Philadelphia PA",type:"Multifamily",year:2025,units:289,role:"Broker (seller rep)",buyer:"Lionheart Realty Group / Lineage Squared / Avery Companies / AMS Equities",notes:"289 units + 8,500 SF commercial (theater company). Originally built 1929 as hotel, repositioned 1998. Miller + Chris Koehler brokered. Lument's Mark Vinitsky arranged financing for purchaser — DIRECT LINK to John Hurley's firm."},
        {property:"1600 Callowhill St",address:"1600 Callowhill St, Philadelphia PA",type:"Multifamily",year:2025,units:95,amount:24500000,role:"Broker (seller rep)",seller:"Ivy Realty",buyer:"Turio Residential Company (Gianni Parente)",notes:"95 loft-style units + 2,500 SF retail. Built 1926, repositioned by Ivy Realty 2019. Adjacent to Rail Park, Benjamin Franklin Parkway. Miller, Steven Schultz, Chris Koehler repped seller."},
        {property:"Jacobs Woods",address:"Lansdale PA",type:"Multifamily",year:2025,amount:73100000,role:"Broker",notes:"$73.1M multifamily sale. Suburban Philadelphia. Part of Newmark Philly MF team's 2025 activity — Erin Miller, Chris Koehler, Marybeth Farris team."},
        {property:"Royal Athena",address:"Bala Cynwyd PA",type:"Multifamily",year:2021,amount:59500000,role:"Broker",notes:"$59.5M suburban Philly multifamily. Bala Cynwyd — Main Line adjacent. Miller team deal."},
        {property:"Canvas (King of Prussia)",address:"King of Prussia PA",type:"Multifamily",year:2022,amount:112500000,role:"Broker",seller:"Bozzuto Development",notes:"$112.5M — Bozzuto Development sold. King of Prussia luxury MF. Miller team deal."},
        {property:"Ember at Berwyn",address:"Berwyn PA",type:"Multifamily",year:2025,role:"Broker",buyer:"Pantzer Properties",notes:"Pantzer Properties acquisition at $386,000/unit. Erin Miller, Chris Koehler, Marybeth Farris of Newmark managed. Highlighted as top 2025 transaction in Newmark Greater Philadelphia Market Overview."},
        {property:"The Gables",address:"Suburban Philadelphia PA",type:"Multifamily",year:2025,role:"Broker",buyer:"Harbor Group International",notes:"Harbor Group acquisition at $248,485/unit. Miller team. Highlighted in Newmark's 2025 Philadelphia market overview."},
      ]
    },
    {name:"Keith Braccia",      firm:"Cushman & Wakefield",           role:"Director, Investment Sales — Capital Markets", markets:"Philadelphia and Pittsburgh MSAs",
      notes:"Education: University of Pennsylvania School of Engineering — BS Systems Engineering, concentration in Financial Systems. Career: Financial Analyst at PMC Property Group (Philadelphia-based adaptive reuse/MF developer — pre-2019) → joined Cushman & Wakefield February 2019 as Director in Capital Markets. At PMC: operations, financial performance analysis, financing/modeling, day-to-day leasing of Philly MF portfolio. At C&W: 15+ transactions in MF, retail, and office across Eastern PA / Southern NJ / Delaware AND Pittsburgh MSA. Part of C&W Philly MF team with Karen Iman, Steven Patterson, Ryan Kelly. Strengths: financial modeling, underwriting, market analysis. BAKER STREET CONNECTION: Covers both Philly AND Pittsburgh markets — unique dual-market coverage. PMC background means he understands the owner/operator perspective from the inside. C&W platform gives him access to national buyers Baker Street needs to reach."
    },
    {name:"Carl Fiebig",        firm:"JLL",                           role:"Senior Managing Director, Capital Markets",  markets:"Philadelphia PA",
      notes:"$266M+ closed. Former HFF (before JLL merger) and Marcus & Millichap. Villanova BS. Leads Philly JLL multifamily capital markets team alongside Samantha Kupersmith and Russell Mapes. CONFIRMED working relationship with Jeff Schaeffer at Alterra — Jeff emailed Carl re: Heinz Lofts deal book Feb 2025. Key institutional MF broker for Post Brothers, Crow Holdings, Colony Hills — major Philly sponsors.",
      dealHistory:[
        {property:"Presidential City",address:"City Ave & Presidential Blvd, Philadelphia PA",type:"Multifamily",year:2022,units:1018,amount:357000000,role:"Broker (seller rep)",seller:"Post Brothers",buyer:"KKR Real Estate Select Trust / Mack Real Estate Group",notes:"$357M — largest multifamily sale in Philadelphia history at time of sale. Post Brothers assumed $290M Société Générale fixed-rate loan (4.3%, 10yr, 2019 vintage) — became an asset as rates rose. JLL team: Mark Thomson, Carl Fiebig, Fran Coyne, Jose Cruz, Tyler Margraf."},
        {property:"Valleybrook at Chadds Ford",address:"Delaware County PA",type:"Multifamily",year:2022,amount:96500000,role:"Broker (seller rep)",seller:"Crow Holdings Capital",buyer:"FPA Multifamily",notes:"$96.5M suburban Philadelphia multifamily. Crow Holdings Capital disposition. Fiebig + Kupersmith team."},
        {property:"Mount Laurel Crossing",address:"Mount Laurel NJ",type:"Multifamily",year:2024,amount:80000000,role:"Broker",notes:"$80M South Jersey multifamily. Kupersmith on team. Burlington County suburban NJ deal."},
        {property:"University of the Arts Portfolio",address:"Philadelphia PA (9 properties)",type:"Mixed-Use / Multifamily Dev",year:2025,amount:74400000,role:"Broker",seller:"University of the Arts",notes:"9-property portfolio sale following UArts surprise bankruptcy/closure. $74.4M. Fiebig + Kupersmith team. Highly complex — institutionally significant."},
        {property:"Heinz Lofts",address:"Pittsburgh PA",type:"Multifamily",year:2025,units:266,role:"Listed / marketed",notes:"CONFIRMED: Jeff Schaeffer (Alterra) emailed Carl Fiebig re: Heinz Lofts deal book Feb 2025. Alterra acquired Heinz Lofts from Federal Capital Partners 2017 ($25.1M). Now marketing with JLL. HOT BAKER STREET BRIDGE: Schaeffer ↔ Fiebig confirmed working relationship."},
      ]
    },
    {name:"Samantha Kupersmith",firm:"JLL",                           role:"Senior Director, Multifamily Investment Sales", markets:"Philadelphia PA",
      notes:"Works directly on Carl Fiebig's JLL team. Former CBRE Philly MF ($300M+ closed) — was on Spencer Yablon's team at CBRE before joining JLL. Lehigh University. PBJ Rising Star 2021. On all major Fiebig JLL deals. Warm path through both Fiebig and Yablon (former colleague).",
      dealHistory:[
        {property:"Presidential City",address:"City Ave & Presidential Blvd, Philadelphia PA",type:"Multifamily",year:2022,units:1018,amount:357000000,role:"Broker (co-rep with Fiebig)",seller:"Post Brothers",buyer:"KKR / Mack Real Estate Group",notes:"On JLL team with Fiebig, Thomson, Cruz, Margraf. $357M record sale."},
        {property:"Valleybrook at Chadds Ford",address:"Delaware County PA",type:"Multifamily",year:2022,amount:96500000,role:"Broker (co-rep with Fiebig)",seller:"Crow Holdings Capital",notes:"$96.5M. Kupersmith + Fiebig together."},
        {property:"Mount Laurel Crossing",address:"Mount Laurel NJ",type:"Multifamily",year:2024,amount:80000000,role:"Broker",notes:"$80M South Jersey deal. Kupersmith on team."},
        {property:"University of the Arts Portfolio",address:"Philadelphia PA",type:"Mixed-Use / Dev",year:2025,amount:74400000,role:"Broker (co-rep with Fiebig)",notes:"9-property UArts portfolio post-bankruptcy closure. Complex institutional transaction."},
        {property:"1623 W Venango St (Nicetown-Tioga)",address:"1623 W Venango St, Philadelphia PA",type:"Multifamily",year:2020,units:30,amount:6050000,role:"Broker (CBRE era — with Yablon)",seller:"LaCorte Properties",buyer:"Twin Lakes Realty",notes:"Still at CBRE with Spencer Yablon when she worked this deal."},
        {property:"Steel Heddle Manufacturing Complex",address:"2100 E Allegheny Ave, Philadelphia PA",type:"Dev Site",year:2022,amount:4500000,role:"Broker (CBRE era — with Yablon)",seller:"AM8 Group",buyer:"Jasper Studios",notes:"257,000 SF historic complex. Opportunity Zone. Kupersmith and Yablon represented seller before she moved to JLL."},
      ]
    },
    {name:"Shelby Zitelman",    firm:"Zitelman Partners",             role:"Sr. VP Business Development",               markets:"Eastern US",
      notes:"Education: Wharton School of Business, University of Pennsylvania — BS Economics, concentration in Entrepreneurial Management, 2007. Career: Ben Franklin Technology Partners (economic development, Philadelphia) → Co-Director at PresenTense (venture philanthropy nonprofit, North America/Israel) → Co-Founder & COO at Soom Foods (food startup, tahini brand — she's still President of the Board) → Sr. VP Business Development at Zitelman Partners (current). PBJ 40 Under 40, 2019. Husband: Dan Stamm. Lives Center City Philadelphia. Firm: Zitelman Partners founded 1985 by Rick Zitelman (her father) — second-generation now. Since 1985: 50+ real estate properties and 20+ operating companies, hundreds of millions in assets. Asset classes: multifamily, student housing, medical/healthcare, office, flex, retail — Eastern US. Highly selective LP/equity investor — passes on 96% of deals seen. Invests directly and aggregates equity/debt to lead or complete capital stacks. Creative on structure and timeframes. BAKER STREET CONNECTION: Shelby is the relationship/BD person — she is the right contact for equity or LP conversations on deals Baker Street brings. Her startup background means she thinks differently than institutional investors."
    },
    {name:"Jeff Schaeffer",     firm:"Alterra Property Group",        role:"SVP, Asset Management",                     markets:"Philadelphia PA",
      notes:"Career: Various CRE roles in Philadelphia market → SVP Asset Management at Alterra Property Group. Alterra is a Philadelphia-based vertically integrated real estate firm with two major platforms: (1) Multifamily — 1,701 Market St conversion (299 units), Heinz Lofts Pittsburgh (266 units), The Arch/1701 Arch St (111 units), Lincoln Square (Broad & Washington Ave); (2) Industrial Outdoor Storage (IOS) — $300M JV with JPMorgan Chase 2019, $100M credit facility Morgan Stanley 2020, built one of largest IOS platforms in Mid-Atlantic. Schaeffer oversees asset management across both. CONFIRMED BAKER STREET BRIDGE: Jeff emailed Carl Fiebig (JLL) about Heinz Lofts deal book in Feb 2025 — confirmed active working relationship. Also: Alterra's Federal Capital Partners co-investment on The Arch and prior Heinz Lofts ownership makes FCP a warm second-degree contact through Schaeffer.",
      dealHistory:[
        {property:"Heinz Lofts",address:"Pittsburgh PA",type:"Multifamily",year:2017,units:266,amount:25100000,role:"Buyer (Alterra)",seller:"Federal Capital Partners",notes:"Alterra acquired from FCP. Currently marketing with Carl Fiebig/JLL — Jeff emailed Carl re deal book Feb 2025. HOT CONFIRMED BRIDGE."},
        {property:"1701 Market St",address:"1701 Market St, Philadelphia PA",type:"Multifamily (Office Conversion)",year:2023,units:299,amount:26200000,role:"Buyer (Alterra)",seller:"Lexington Industrial Trust",notes:"299-unit office-to-residential conversion. Alterra acquisition from Lexington."},
        {property:"The Arch / 1701 Arch St",address:"1701 Arch St, Philadelphia PA",type:"Multifamily",year:2012,units:111,role:"Developer (Alterra)",notes:"111-unit development with Federal Capital Partners. Early Alterra project."},
        {property:"Alterra IOS Platform",address:"Mid-Atlantic / National",type:"Industrial Outdoor Storage",year:2019,role:"Developer/Operator",notes:"$300M JV with JPMorgan Chase 2019. $100M credit facility Morgan Stanley 2020. Alterra built major IOS platform alongside MF — Jeff oversees both."},
      ]
    },
    {name:"Jason Mandel",       firm:"RCCB Law (Royer Cooper Cohen Braunfeld)",  role:"Partner, Real Estate Group",  markets:"Greater Philadelphia, New York",
      notes:"Education: Unknown publicly — law degree required for Partner at major firm. Career: Armstrong Teasdale (early career) → Kurtz & Partners (20+ years as CRE transactional attorney) → RCCB Law / Royer Cooper Cohen Braunfeld — Partner, Real Estate Group (current). 25+ years total CRE transactional law. Represents lenders, borrowers, sponsors, AND developers — both sides of the same table on different deals. Asset classes: multifamily, hotels, self-storage, industrial outdoor storage (IOS), telecom/colocation, mixed-use development. Notable deal types handled: $29M 26-parcel Philly MF portfolio, $20M student housing near Temple, $13M 72-unit Philly apartment, $54M industrial construction financing Philly, $200M telecom building acquisition, $15M NJ opportunity fund (3 commercial properties). Golf course acquisition in Middletown DE. Inside deals on both sides of the capital table — knows before anyone else when a deal is in trouble or changing hands. BAKER STREET CONNECTION: Jason is on both lender AND borrower sides — if his firm represents a distressed borrower, he is the fastest path to a conversation. Every sponsor Baker Street targets may have run through Mandel's firm.",
      dealHistory:[
        {property:"26-Parcel Multifamily Portfolio",address:"Philadelphia PA",type:"Multifamily",amount:29000000,role:"Counsel",notes:"$29M, 26-parcel Philadelphia MF portfolio. Named in Mandel's bio. Represented one or both sides."},
        {property:"90-Unit Student Housing",address:"Near Temple University, Philadelphia PA",type:"Student Housing",amount:20000000,role:"Counsel",notes:"$20M student housing acquisition near Temple. Named in Mandel's bio."},
        {property:"72-Unit Apartment Building",address:"Philadelphia PA",type:"Multifamily",amount:13000000,role:"Counsel",notes:"$13M, 72-unit apartment Philadelphia. Named in Mandel's bio."},
        {property:"Industrial Construction Financing",address:"Philadelphia PA",type:"Industrial",amount:54000000,role:"Counsel",notes:"$54M industrial construction financing, Philadelphia. Named in bio — construction loan counsel."},
        {property:"Telecom Building Acquisition",address:"Northern NJ",type:"Commercial / Telecom",amount:200000000,role:"Counsel",notes:"$200M, 780,000 SF telecom building. Named in Mandel's bio — major commercial deal."},
        {property:"NJ Opportunity Fund",address:"Northern NJ",type:"Mixed-Use Commercial",amount:15000000,role:"Counsel",notes:"$15M opportunity fund — 3 commercial properties in northern NJ. Named in bio."},
      ]
    },
    {name:"Eric Ramirez",       firm:"ACORE Capital",                 role:"Managing Director, Head Eastern Region Originations", markets:"New York NY (Eastern US)",
      notes:"Education: Drew University — BA Economics. Career: Wells Fargo Real Estate Capital Markets — Vice President, CMBS ($5B+ CMBS originations, $500M balance sheet loans) → Co-Founded IH Capital (proprietary CMBS origination platform, $1.5B originated in 2 years alongside Iron Hound alumni network) → ACORE Capital — MD, Head of Eastern Region Originations (current). ACORE Capital: major bridge/transitional/construction lender, $20B+ originated, HQ Los Angeles. Eastern Region covers NYC, Mid-Atlantic, Southeast — all Baker Street's markets. DIRECT BRIAN OVERLAP: Eric at IH Capital and Brian at Iron Hound Management were in the same NYC CMBS/restructuring world simultaneously — direct peer overlap. ACORE lends on distressed and transitional assets = intro to their distressed borrowers AND capital source for recaps/bridge financing Baker Street structures.",
      dealHistory:[
        {property:"The Hartby (788 Willoughby Ave)",address:"788 Willoughby Ave, Brooklyn NY",type:"Multifamily",year:2024,units:205,amount:72200000,role:"Lender (ACORE)",borrower:"Property Resources Corporation (PRC)",notes:"$72.2M bridge loan. 205-unit conversion from St. John's College buildings. Ackman-Ziff arranged for ACORE. PRC is repeat ACORE borrower."},
        {property:"Miroza at Ridge Hill",address:"Yonkers NY",type:"Multifamily",year:2025,amount:145000000,role:"Lender (ACORE)",borrower:"Azorim North America",notes:"$145M — large suburban NYC multifamily. Azorim is Israeli developer with US platform. ACORE Eastern Region deal."},
        {property:"CityHouse Ashburn Station",address:"Ashburn VA",type:"Multifamily",year:2025,amount:89200000,role:"Lender (ACORE)",borrower:"American Real Estate Partners / Rithm Capital / GreenBarn",notes:"$89.2M. Mixed institutional borrower group. Northern Virginia suburban MF. ACORE Eastern Region deal."},
        {property:"National Place",address:"Washington DC",type:"Multifamily / Mixed-Use",year:2021,amount:138900000,role:"Lender (ACORE)",borrower:"Quadrangle Development Corp",notes:"$138.9M DC deal. Quadrangle is a repeat DC developer. ACORE Eastern Region."},
        {property:"Ideal Building",address:"Jamaica, Queens NY",type:"Multifamily",year:2024,amount:69200000,role:"Lender (ACORE)",borrower:"KABR Group",notes:"$69.2M. KABR is active NYC/NJ developer. Jamaica Queens location."},
        {property:"77 Water Street",address:"77 Water Street, NYC",type:"Commercial / Conversion",year:2022,amount:127500000,role:"Lender (ACORE)",borrower:"Sage Realty / Principal Real Estate",notes:"$127.5M. Major NYC office/conversion deal. Sage Realty is repeat ACORE client."},
        {property:"The Campanile (1155 Peachtree St NE)",address:"Atlanta GA",type:"Multifamily",year:2021,amount:75000000,role:"Lender (ACORE)",borrower:"Dewberry Group",notes:"$75M Atlanta MF. Dewberry Group — Atlanta developer."},
        {property:"5 JCPenney Stores (Mid-Atlantic)",address:"Mid-Atlantic region",type:"Retail / Adaptive Reuse",year:2022,amount:53000000,role:"Lender (ACORE)",borrower:"Meridian Group / Martin-Diamond",notes:"$53M — 5 former JCPenney stores Mid-Atlantic. Adaptive reuse play. Meridian Group is active DC/Mid-Atlantic developer."},
        {property:"Waterview III",address:"St. Petersburg FL",type:"Multifamily",year:2022,amount:20500000,role:"Lender (ACORE — mezz)",notes:"$20.5M mezzanine loan, 363-unit construction. St. Petersburg FL. ACORE mezz position."},
      ]
    },
    {name:"Danny Volk",         firm:"Vantage Real Estate Advisors",  role:"Founder",                                   markets:"New York NY, Florida",
      notes:"Education: Hofstra University — BS Finance, 1997–2001. Career: Managing Partner at EMM Group (now Catch Hospitality Group) — 20+ years in F&B operations and hospitality real estate → Founded Vantage Real Estate Advisors. EMM Group/Catch Hospitality is behind Catch restaurant brand, major NYC hospitality venues. At Vantage: tenant and landlord representation, concept development, strategic F&B consulting, site search and selection, operations analysis — across NYC and Florida. Deep relationships with prominent chefs, operators, and hospitality-focused landlords and investors. Owner-operator mentality distinguishes him from pure brokers. 11+ transactions closed publicly. BAKER STREET CONNECTION: Hotel and hospitality property owners with debt distress often need F&B strategy as part of the workout — Volk is the contact for any deal with a hotel, restaurant, or retail component where leasing/activation is the key to the debt story.",
      dealHistory:[
        {property:"Martinique Hotel (1 West 32nd St)",address:"1 W 32nd St, Nomad District, NYC",type:"Hotel / Retail",role:"Advisor",borrower:"Burnett Equities",notes:"Leased 32,000 SF dormant ground floor retail in under 90 days to create positive cash flow, enabling debt securitization and property sale. New tenant mix included Press Club Grill by Chef Franklin Becker. Volk + Andy Kim executed. Burnett Equities closed the sale as a result."},
      ]
    },
    {name:"Matthew Stefanski",  firm:"Berkadia",                      role:"Senior Managing Director, Philly MF Investment Sales", markets:"Philadelphia PA, Mid-Atlantic",
      notes:"Education: Unknown publicly. Career: M&T Bank — commercial real estate lending → CBRE Philadelphia — Vice President, Multifamily Capital Markets (institutional MF investment sales) → Berkadia — Senior Managing Director (current), Co-Head Philadelphia MF Investment Sales with Zach Pierce. At Berkadia: 100+ transactions, 15,000+ units sold, $2B+ closed. Berkadia is a Berkshire Hathaway + Leucadia National (now Jefferies) JV — one of the largest multifamily investment banks in the US. Covers entire Mid-Atlantic and greater Philadelphia MSA. Stefanski + Pierce operate as a unified platform — all deals are co-listed. Key client: Morgan Properties (bought DePaul 3,434-unit portfolio 2024). ROB CONNECTION: Iron Hound worked alongside Berkadia on Mid-Atlantic MF workout and disposition deals — Rob knows the Berkadia platform from the restructuring side. Steve Comly at Newmark also spent 13 years at Berkadia — warm overlapping network.",
      dealHistory:[
        {property:"DePaul Management Co PA Portfolio",address:"Pennsylvania (11 properties)",type:"Multifamily",year:2024,units:3434,role:"Broker (seller rep)",seller:"DePaul Management Company",buyer:"Morgan Properties",notes:"11-property, 3,434-unit PA portfolio. One of largest PA MF portfolio trades in years. Morgan Properties is the region's biggest MF owner. Stefanski + Pierce co-led."},
        {property:"Blue Course Commons",address:"State College PA",type:"Multifamily",year:2024,units:150,amount:24500000,role:"Broker (seller rep)",seller:"College Town Communities",notes:"$24.5M. State College/Penn State market — student-adjacent suburban MF. Berkadia Philly team."},
        {property:"The Overlook",address:"Camp Hill PA",type:"Multifamily",year:2025,units:288,role:"Broker (seller rep)",buyer:"The Apartment Gallery",notes:"288-unit suburban Harrisburg PA. The Apartment Gallery as buyer. 2025 deal."},
        {property:"The Reserve at Sawmill",address:"Milford DE",type:"Multifamily",year:2025,units:149,amount:23200000,role:"Broker",notes:"$23.2M, 149-unit Delaware multifamily. Milford DE — Berkadia Philly covering tri-state."},
        {property:"Halstead Place Apartments",address:"Clinton NJ",type:"Multifamily",year:2024,role:"Broker (seller rep)",seller:"Merion Realty Partners",notes:"Clinton NJ garden apartments. Merion Realty Partners seller. Berkadia Philly NJ coverage."},
        {property:"Birchwood Commons",address:"Bethlehem PA",type:"Multifamily",year:2019,units:96,role:"Broker",notes:"96-unit Bethlehem PA multifamily. Lehigh Valley market — part of Berkadia Philly broader PA coverage."},
      ]
    },
    {name:"Zach Pierce",        firm:"Berkadia",                      role:"Senior Managing Director, Co-Head MF Investment Sales", markets:"Philadelphia PA, Mid-Atlantic",
      notes:"Education: Unknown publicly. Career: Marcus & Millichap (investment sales, early career) → JLL (multifamily capital markets, Philadelphia) → Berkadia — Senior Managing Director, Co-Head Philadelphia MF Investment Sales with Matt Stefanski (current). At Berkadia: 250+ transactions, $3B+ closed, 15+ years. Former JLL background means he worked alongside Carl Fiebig at some point — warm JLL bridge. Co-head with Stefanski — all deals operated jointly. Coverage: Philadelphia, Mid-Atlantic, Delaware Valley, Central PA, NJ. ROB CONNECTION: Rob's Iron Hound worked alongside Berkadia on Mid-Atlantic MF workout and disposition deals. Warm path into Mid-Atlantic MF owner network through Pierce + Stefanski.",
      dealHistory:[
        {property:"DePaul Management Co PA Portfolio",address:"Pennsylvania (11 properties)",type:"Multifamily",year:2024,units:3434,role:"Broker (co-rep with Stefanski)",seller:"DePaul Management Company",buyer:"Morgan Properties",notes:"3,434 units — co-led with Stefanski."},
        {property:"Blue Course Commons",address:"State College PA",type:"Multifamily",year:2024,units:150,amount:24500000,role:"Broker (co-rep with Stefanski)",seller:"College Town Communities",notes:"$24.5M State College PA."},
        {property:"The Overlook",address:"Camp Hill PA",type:"Multifamily",year:2025,units:288,role:"Broker (co-rep with Stefanski)",buyer:"The Apartment Gallery",notes:"288 units suburban Harrisburg. 2025 deal."},
        {property:"The Reserve at Sawmill",address:"Milford DE",type:"Multifamily",year:2025,units:149,amount:23200000,role:"Broker",notes:"$23.2M Milford DE."},
      ]
    },
    {name:"Philip Cohen",       firm:"Mansfield Equities",            role:"President & Founder",                        markets:"Los Angeles CA, Miami FL, San Francisco CA (national)",
      notes:"Education: University of Michigan — undergraduate; NYU Stern School of Business — MBA. Career: Ackman-Ziff Real Estate Group (NYC debt/equity placement) → Founded Mansfield Equities 2006. Third-generation real estate entrepreneur — family background in RE dating back to grandfather. Mansfield arranges debt, mezzanine, preferred equity, and JV equity for CRE developers and sponsors nationwide. Also founded Real Estate Capital Alliance (RECA) — 65+ originators across 15 markets, $25B+ arranged collectively. Also involved in Commercial Finance Broker Network (CFBN). Based in Los Angeles with offices in Miami and San Francisco — national platform. Particularly active in multifamily, mixed-use, hospitality, and retail recapitalizations. BAKER STREET CONNECTION: Brian's UBS CMBS origination background directly overlaps with the kind of capital sources Mansfield/RECA plugs into. If Baker Street needs to quickly access 40+ lenders on a deal, Philip's RECA network is the parallel path. Also: Ackman-Ziff (his former firm) also arranged financing for some of ACORE Capital's deals — indirect Eric Ramirez overlap."
    },
    {name:"Derek Weissman",     firm:"Procida Funding & Advisors",    role:"Partner & Head of Asset Management",         markets:"Englewood Cliffs NJ, Philadelphia PA, NYC, Mid-Atlantic",
      notes:"Education: Unknown publicly. Career: Various CRE finance and asset management roles → Joined Procida Funding & Advisors 2015 as VP/Director of Asset Management → Named Partner ~2022. Procida: private alternative lender founded by William Procida. Specializes in construction, bridge, and DIP (debtor-in-possession) loans. $800M+ underwritten/closed/managed. $500M+ portfolio under active management. 700+ residential units developed, 1M+ SF commercial. Key specialties: historic building renovations, environmentally challenged sites, ground-up construction in difficult infill markets, bankruptcy/DIP situations. Notable borrowers include Eric Blumenfeld (The Met Philly, Divine Lorraine), Dean Geibel/Liberty Harbor North (Gulls Cove II, Jersey City). Also: Tower at Mural West, Hudson Valley Brewery, RCA Victor Records Building (Camden NJ). ROB CONNECTION: Procida DIP loans are directly in Rob's Iron Hound workout world — Rob would have seen Procida on the other side of restructuring tables. Warm bridge into Procida's existing distressed borrowers who need additional capital.",
      dealHistory:[
        {property:"The Met Philadelphia (Metropolitan Opera House)",address:"858 N Broad St, Philadelphia PA",type:"Multifamily / Historic Renovation",year:2018,amount:56000000,role:"Lender (Procida)",borrower:"Eric Blumenfeld / EB Realty Management",notes:"$56M Procida construction/bridge loan. Eric Blumenfeld — major Philly historic renovation developer. Iconic North Broad St redevelopment."},
        {property:"Divine Lorraine Hotel",address:"N Broad St, Philadelphia PA",type:"Mixed-Use / Historic Renovation",year:2015,amount:34750000,role:"Lender (Procida)",borrower:"Eric Blumenfeld / EB Realty Management",notes:"$34.75M. Same Eric Blumenfeld repeat client. Historic Broad Street landmark conversion — apartments + hotel + restaurant."},
        {property:"Gulls Cove II",address:"201 Marin Blvd, Jersey City NJ",type:"Multifamily",year:2017,amount:68500000,role:"Lender (Procida)",borrower:"Dean Geibel / Liberty Harbor North",notes:"$68.5M ground-up construction loan. Jersey City waterfront. Liberty Harbor North development. Geibel is repeat NJ developer."},
        {property:"The View at Middlesex",address:"Middlesex NJ",type:"Multifamily",amount:39000000,role:"Lender (Procida)",notes:"$39M Procida loan. NJ suburban multifamily construction."},
        {property:"Washington Lofts",address:"Carteret NJ",type:"Multifamily",amount:38500000,role:"Lender (Procida)",notes:"$38.5M Procida loan. Carteret NJ multifamily construction."},
        {property:"Hudson Valley Brewery",address:"Beacon NY",type:"Commercial / Historic Renovation",role:"Lender (Procida)",notes:"Historic renovation loan — brewery adaptive reuse. Procida specialty: environmental/complex renovations."},
        {property:"RCA Victor Records Building",address:"Camden NJ",type:"Mixed-Use / Historic",role:"Lender (Procida)",notes:"Historic RCA Victor complex renovation loan. Camden NJ — cross-river from Philly. Complex historic rehab."},
      ]
    },
    {name:"Spencer Yablon",     firm:"CBRE",                          role:"Senior Vice President, Multifamily Capital Markets", markets:"Philadelphia PA (PA/NJ/DE)",
      notes:"$9.25B+ in MF investment sales. 21+ years CRE. Co-leads CBRE Philly MF Capital Markets team with Robert Miller (EVP) and John McFadden (EVP) — $11.5B+ team total, 115,000+ units sold. Former Regional Manager Marcus & Millichap Philadelphia ($4B+, 850+ closings). Covers PA/NJ/DE institutional and private MF dispositions. Lehigh University 1999. BAKER STREET CONNECTION: Samantha Kupersmith was on Spencer's CBRE team before moving to JLL's Carl Fiebig team — warm cross-firm path. Spencer repped Brookfield in 2025 sale of Lofts at 1835 Arch. Key intel source on who is selling big institutional Philly MF blocks and what pricing looks like.",
      dealHistory:[
        {property:"Lofts at 1835 Arch",address:"1835 Arch St, Philadelphia PA",type:"Multifamily",year:2025,units:191,amount:null,role:"Broker (seller rep)",seller:"Brookfield Properties",buyer:"GY Properties (local developer)",notes:"Former Bell Telephone building conversion — 191-unit luxury loft tower across from Comcast Technology Center. Brookfield disposition. Yablon quoted: 'cautious optimism' in Philly capital markets."},
        {property:"Steel Heddle Manufacturing Complex",address:"2100 E Allegheny Ave, Philadelphia PA",type:"Dev Site / Historic",year:2022,amount:4500000,role:"Broker (seller rep)",seller:"AM8 Group LLC",buyer:"Jasper Studios",notes:"257,000 SF four-building historic complex in Federal Opportunity Zone. Yablon and Kupersmith represented seller. Jasper Studios redevelopment."},
        {property:"1623 W Venango St",address:"1623 W Venango St, Nicetown-Tioga, Philadelphia PA",type:"Multifamily",year:2020,units:30,amount:6050000,role:"Broker (seller rep)",seller:"LaCorte Properties",buyer:"Twin Lakes Realty",notes:"New modular construction adjacent to Temple University Health Sciences Campus. CBRE team: Yablon, Kupersmith, McFadden, Miller, Sam Zell, Brad Megay."},
        {property:"ICON at 1616 Walnut",address:"1616 Walnut St, Center City Philadelphia PA",type:"Multifamily",year:2019,units:206,role:"Exclusive listing broker",notes:"Art Deco 1920s landmark — 206-unit luxury, 22,848 SF retail, 142-space garage. Rehabilitated 2014. Yablon retained as exclusive disposition agent."},
        {property:"3601 Market St",address:"3601 Market St, University City, Philadelphia PA",type:"Multifamily",year:2017,role:"Broker",buyer:"San Francisco-based investor",notes:"Class A new-construction (completed 2016) sold to West Coast institutional. Yablon cited as example of institutional appetite for stabilized core+ in Philly over value-add."},
      ]
    },
    {name:"Russell Mapes",      firm:"JLL",                           role:"Senior Director, Capital Markets Debt Advisory",    markets:"Philadelphia PA (PA/NJ/DE/MD)",
      notes:"Debt placement specialist for MF owners across PA, NJ, DE, MD. 12+ years CRE. JLL Philadelphia Capital Markets office. Former acquisitions analyst at LEM Capital (value-add MF underwriting nationwide). Agency, life company, bridge, and structured finance. BAKER STREET CONNECTION: Same JLL Philadelphia office as Carl Fiebig and Samantha Kupersmith — frequent collaborators on sell-side + debt advisory on same deals. Intro path warm through either Fiebig or Kupersmith. Active on suburban Philly suburban NJ suburban deals — exactly Baker Street's distressed target zone.",
      dealHistory:[
        {property:"300-Unit MF Construction (Burlington County)",address:"Burlington County, NJ",type:"Multifamily",year:2022,units:300,amount:47000000,role:"Debt Advisor",lender:"Wells Fargo",notes:"3-year floating-rate construction loan for approx. 300-unit garden community. Avg unit size 971 SF. Amenities: fitness, pool, courtyard. Anticipated delivery Q2 2024. Mapes placed through JLL."},
        {property:"Bryn Mawr Apartments",address:"Bryn Mawr, PA",type:"Multifamily",year:2025,units:106,role:"Investment Sales / Debt",notes:"106-unit value-add suburban Philly — listed and marketed by Mapes through JLL Capital Markets Philadelphia. Active 2025 listing."},
        {property:"Saxum Northern Liberties Phase I (711-735 N Front St)",address:"711-735 N Front St, Northern Liberties, Philadelphia PA",type:"Multifamily",year:2023,units:279,amount:77500000,role:"Debt Advisor (JLL team)",lender:"US Life Insurance Co",developer:"Saxum Real Estate",notes:"Phase I of 466-unit two-phase Northern Liberties development. 7-story, 8,449 SF retail. 3-year floating rate non-recourse. JLL team: Michael Klein, Ryan Ade, Tom Didio, Gerard Quinn, Blaine Fleming — Mapes's office colleagues. Delivered Sept 2024."},
        {property:"Saxum Northern Liberties Phase II (700 N Delaware Ave)",address:"700 N Delaware Ave, Northern Liberties, Philadelphia PA",type:"Multifamily",year:2023,units:187,amount:55700000,role:"Debt Advisor (JLL team)",lender:"US Life Insurance Co",developer:"Saxum Real Estate",notes:"Phase II of same two-block Northern Liberties development. 7-story, 7,803 SF retail. Dec 2023 close. Delivery Aug 2025. Same JLL team."},
        {property:"Westampton Apartments (275-Unit Class A)",address:"Westampton, Burlington County NJ",type:"Multifamily",year:2025,units:275,amount:50000000,role:"Debt Advisor (JLL team)",lender:"Life Insurance Co",notes:"Permanent fixed-rate loan for Class A suburban community, 20 miles from Center City Philly. JLL team: Klein, Quinn."},
      ]
    },
    {name:"Steve Comly",        firm:"Newmark",                       role:"Executive Managing Director, Capital Markets Debt & Structured Finance", markets:"Philadelphia PA",
      notes:"Joined Newmark 2020 from Berkadia (13 yrs as VP, $3B+ closed). $10B+ total career financings. Full capital spectrum: Fannie Mae, Freddie Mac, FHA, Life Companies, CMBS, banks, bridge funds — for multifamily and commercial. Works alongside Jim Badolato, Matt Cullison, and Mike McKee on Newmark Philly debt team. Works on same platform as Erin Miller (investment sales). BAKER STREET CONNECTION: 13 years at Berkadia = same shop and relationships as Matt Stefanski and Zach Pierce — major warm bridge to Berkadia's Mid-Atlantic MF workout and deal pipeline. Also: sits on same Newmark platform as Erin Miller — frequent debt-plus-sales combo on same assets. Previously: commercial real estate analyst at Nomura Securities and Credit Suisse. Fairfield University 2003.",
      dealHistory:[
        {property:"400 Market St (Office-to-Residential Conversion)",address:"400 Market St, Philadelphia PA",type:"Mixed-Use / Conversion",year:2024,units:176,role:"Debt Advisor",notes:"Floors 2-12 converting to 176 modern apartments. Comly and Badolato arranged financing for the conversion. Highlighted in Newmark's Greater Philadelphia Multifamily Market Overview 2025."},
        {property:"Rockwell at Crown",address:"Gaithersburg, Maryland",type:"Multifamily",year:2025,units:335,amount:67500000,role:"Debt Advisor (team lead: Badolato)",lender:"Fannie Mae",notes:"$67.5M Fannie Mae refinance. Sentinel Real Estate Corporation borrower. Badolato-led team. Comly's collaborative Newmark platform deal."},
        {property:"Wentworth Apartment Homes",address:"5411 McGrath Blvd, North Bethesda MD",type:"Multifamily",units:312,amount:72000000,year:2021,role:"Debt Advisor (Badolato-led)",lender:"BayernLB",notes:"$72M refi of Class A high-rise. LCOR borrower. German lender BayernLB. Badolato team — Comly's same Newmark Philly debt group."},
        {property:"6250 Baltimore Ave (Industrial)",address:"6250 Baltimore Ave, Delaware County PA",type:"Industrial",year:2024,amount:59000000,role:"Debt Advisor (Badolato-led)",notes:"$59M sale and financing of 450,000 SF industrial. Velocity Venture Partners seller. Badolato + Adam Rudman arranged acquisition financing on behalf of buyer."},
      ]
    },
    {name:"Ken Wellar",         firm:"GREA (Rittenhouse Realty Advisors)", role:"Founding Managing Partner",               markets:"Philadelphia PA, Northeast US",
      notes:"Co-founding Managing Partner of GREA Mid-Atlantic, formerly Rittenhouse Realty Advisors (est. 2013). Philly's dominant boutique MF brokerage. 20+ years MF experience. 33,000+ units brokered, $4B+ in consideration career total. 85 transactions closed by GREA team in 2025. Works with Corey Lonberger (co-founder), Douglas Sitt, Mark Duszak, Alan Krawitz. Temple University. Member: NMHC, ULI, PA/NJ/DE Apartment Associations, YPO. BAKER STREET CONNECTION: Wellar and CBRE's Yablon both quoted in same Nov 2025 MPN article on Philly MF revival — track exact same deals and buyers. Wellar's GREA is the boutique private-seller axis while CBRE/JLL/Newmark are institutional — different deal profiles, both critical. Rob's Iron Hound world handled workout deals that Wellar and his private sellers would have been on the other side of.",
      dealHistory:[
        {property:"Hamilton Court",address:"University City, Philadelphia PA",type:"Student Housing / MF",year:2022,units:103,beds:295,amount:87000000,role:"Broker (seller rep)",seller:"Post Brothers",buyer:"Undisclosed",notes:"$87M — one of largest Philly student housing deals ever. 103 units/295 beds near University of Pennsylvania. 21,400 SF ground floor retail. Post Brothers had acquired 2015 and completed $21M in improvements. GREA/RRA represented seller."},
        {property:"Spring Lofts",address:"1217-35 Spring Garden St / 1222-30 Ridge Ave, Philadelphia PA",type:"Multifamily Mixed-Use",year:2022,units:73,amount:22800000,role:"Broker",buyer:"Family office (new to Philly market)",notes:"73 units + 43 parking + 15,016 SF commercial. Spring Arts/Callowhill/Loft District. Near Rail Park. Wellar and Lonberger repped."},
        {property:"The Vault",address:"5801 Ridge Ave, Manayunk/Roxborough, Philadelphia PA",type:"Multifamily",year:2022,units:59,amount:19250000,role:"Broker (seller rep)",seller:"Stamm Development Group",buyer:"NY-based 1031 exchange buyer",notes:"$325,000/unit. 59 units + 4,300 SF commercial. New construction. Wellar: '1031 buyers chasing quality assets.' Mark Duszak also on deal."},
        {property:"The Edison (312 N 2nd St)",address:"312 N 2nd St, Old City, Philadelphia PA",type:"Multifamily",year:2022,units:24,amount:9950000,role:"Broker",buyer:"All-cash 1031 exchange buyer",notes:"24 luxury units master-leased by Sonder. 6.5 yrs left on master lease. New construction 2021. Wellar: 'Second Sonder building we sold recently.' Wellar, Lonberger, Duszak, Krawitz."},
        {property:"Center City Portfolio (WashWest / Rittenhouse)",address:"902 Spruce St, 716 S 2nd St, 715 South St, 750-52 Martin St, 2027 Pine St, Philadelphia PA",type:"Multifamily Mixed-Use",year:2022,units:22,amount:7900000,role:"Broker",notes:"Scattered portfolio in Washington Square West and Rittenhouse Square. Wellar: 'Got a deal done without retrades in the current debt environment.'"},
        {property:"Bristol Gardens",address:"1405 Veterans Hwy, Bristol PA",type:"Multifamily",year:2023,units:392,amount:40750000,role:"Broker",notes:"#1 Philadelphia Business Journal apartment deal of 2023. 34 buildings on 30-acre site. First-time ever offered for sale by one family since construction. GREA represented seller."},
        {property:"1001 Pine St",address:"1001 Pine St, Center City, Philadelphia PA",type:"Multifamily",year:2025,units:21,amount:5200000,role:"Broker (seller rep)",notes:"21-unit Center City building. Nov 2025 closing — example of market revival Wellar was tracking. Wellar directly repped seller."},
        {property:"Fairmount Portfolio",address:"Fairmount neighborhood, Philadelphia PA",type:"Multifamily",year:2025,amount:5700000,role:"Broker (seller rep)",notes:"Fairmount portfolio — multiple buildings. Nov 2025 closing alongside 1001 Pine deal. Market momentum building."},
        {property:"Fox Ridge Apartments / Lake View Park Apartments",address:"Limerick PA / Royersford PA",type:"Multifamily",year:2025,role:"Broker (seller rep)",buyer:"AION Partners (New York)",notes:"Two suburban Philly communities — original builders selling for first time ever. 98%+ occupancy. AION Partners buyer — NY-based owner/operator with strong Mid-Atlantic track record. Corey Lonberger led marketing."},
        {property:"The Venetian (Student Housing — FSU)",address:"235 S Ocala Rd, Tallahassee FL",type:"Student Housing",year:2023,units:96,beds:384,amount:22700000,role:"Broker (seller rep)",seller:"FPA Multifamily",buyer:"NY-based family office (1031)",notes:"GREA's national student housing platform. Wellar: 'enrollment growth pushing value, new investors from out of town.' FSU adjacent."},
      ]
    },
    {name:"Justin Lupo",        firm:"ICON Real Estate Advisors",     role:"Managing Director",                              markets:"NJ, Eastern PA, Mid-Atlantic/Northeast",
      notes:"MF investment sales — NJ and eastern PA. Career: Kislak (2014–2023) → Cushman & Wakefield (Executive MD, co-led Northeast MF platform) → ICON Real Estate Advisors (current). At Kislak: all-time leading salesperson in firm's 100+ year history. $450M+ career sales. 2022 Producer of the Year ($130M, 12+ deals, 650+ units — best year in Kislak history). 2018 + 2020 Salesperson of the Year. Monmouth University. BAKER STREET CONNECTION: Lupo's Kislak deals included South Jersey portfolios, central NJ, and eastern PA — overlapping geography with Rob's Iron Hound Mid-Atlantic workout deals and Baker Street's Trepp deal sourcing. Lupo's longtime client Westover Companies (buyer of 326-unit Sicklerville/Bridgeton/Burlington portfolio) is exactly the type of distressed portfolio buyer Baker Street wants to know. Strong NJ suburban multifamily operator and buyer network.",
      dealHistory:[
        {property:"Creekside North + South Apartments",address:"NJ (exact address undisclosed)",type:"Multifamily",year:2022,units:261,amount:51000000,role:"Broker",notes:"Two neighboring communities — 261 units combined. $51M. Lupo's largest single deal at Kislak. Part of record $130M 2022 year."},
        {property:"Newton NJ Multifamily Portfolio",address:"Newton, NJ",type:"Multifamily",year:2022,units:115,amount:22500000,role:"Broker",notes:"115-unit portfolio in Newton NJ. Part of Lupo's 2022 record year."},
        {property:"South Jersey 326-Unit Portfolio (Regency House / Upper Deerfield / Polo Ridge)",address:"304 Erial Rd Sicklerville NJ / 23 McCormick Blvd Bridgeton NJ / 1210 N Rte 130 Burlington Township NJ",type:"Multifamily",year:2019,units:326,amount:24500000,role:"Broker (both sides)",seller:"Mercer Management",buyer:"Westover Companies",notes:"Off-market. Regency House (195 units, Camden County), Upper Deerfield Estates (67 units active adult, Cumberland County), Polo Ridge (64 units, Burlington County — ~10 miles from Philly). Lupo repped both parties. Westover = longtime Lupo client."},
        {property:"Morristown Multifamily (Kamson Corp)",address:"Morristown NJ",type:"Multifamily",year:2022,amount:8550000,role:"Broker",seller:"Kamson Corporation",notes:"Kislak deal with Pucci. Kamson Corp is longtime Kislak institutional client."},
        {property:"NJ/PA Multifamily (Kislak 2019–2022 portfolio)",address:"Central NJ and Eastern PA",type:"Multifamily",year:2022,role:"Broker",notes:"12+ multifamily sales in 2022 alone, 650+ units in NJ and PA, $130M total. Career $450M+ closed. Deep NJ suburban and eastern PA operator/buyer network."},
      ]
    },
    {name:"John Hurley",        firm:"Lument",                        role:"Director, Originations",                         markets:"Philadelphia PA suburbs, Mid-Atlantic (DC-based)",
      notes:"Agency lender — Fannie Mae DUS, Freddie Mac Optigo, FHA, USDA. Lument is subsidiary of ORIX Corporation USA. Joined Lument legacy firm Hunt Real Estate Capital 2013 as underwriting analyst. Underwrote $1.5B+ in closings before becoming VP 2016. Now Director. Northwestern BA Economics, ESADE Barcelona MBA. Based Washington DC but actively originating into Philadelphia MSA. Specialties: multifamily, affordable housing, seniors housing/healthcare. BAKER STREET CONNECTION: Lument is a direct agency capital source — Fannie/Freddie/FHA on distressed refi and acquisition scenarios. John's repeat client Silverstone Properties (NJ-based, 1,500 units under management) is exactly the type of active buyer Baker Street wants in its CRM. John's background in DIP underwriting at Hunt aligns with Rob's Iron Hound workout world — distressed-to-agency takeout is his lane.",
      dealHistory:[
        {property:"Affordable Housing Community — Levittown",address:"Levittown PA (20 miles NE of Center City Philadelphia)",type:"Affordable Multifamily",year:2025,amount:24800000,role:"Originator",lender:"Freddie Mac (TAH — Targeted Affordable Housing)",borrower:"Affiliate of Silverstone Properties (NJ)",notes:"$24.8M Freddie Mac TAH loan. Acquisition financing. 5-year term, 35-year amortization. Built 1972. All units rent-and-income restricted. 'Closed two months after application' — Hurley. Zach Schwartz / Brook Hollow Capital was mortgage broker."},
        {property:"Lavana Falls Apartments",address:"Levittown PA",type:"Multifamily",year:2025,units:250,role:"Originator",lender:"Freddie Mac (conventional)",borrower:"Silverstone Properties",notes:"250-unit garden-style community. Freddie Mac refi/bridge takeout — refinanced existing Lument bridge loan from 2022. Hurley structured preferred equity-like component behind Freddie first lien. 5-year term, 2 yrs IO, 30-yr amortization. Same repeat Silverstone client."},
        {property:"Lument bridge loan (Lavana Falls)",address:"Levittown PA",type:"Multifamily",year:2022,units:250,role:"Originator",lender:"Lument (bridge)",borrower:"Silverstone Properties",notes:"Original bridge loan for Lavana Falls acquisition 2022 — refinanced out 2025 into Freddie conventional. Shows full-cycle Hurley-Silverstone relationship: bridge → agency takeout."},
      ]
    },
];
